#####################################################
##
## Base
##
#####################################################

persistence.repositoryFactory=eapli.alsafe.persistence.impl.jpa.JpaRepositoryFactory
#persistence.repositoryFactory=eapli.alsafe.persistence.impl.inmemory.InMemoryRepositoryFactory
persistence.persistenceUnit=eapli.alsafe
ui.menu.layout=vertical
HighCaloriesDishLimit=300
scomp.dir=../SCOMP
scomp.binary=flight_simulation
simulation.reports.input.dir=../SCOMP/reports
monthly.reports.output.dir=../SCOMP/reports
