#####################################################
##
## Remote Access Application Properties
##
#####################################################

persistence.repositoryFactory=eapli.alsafe.persistence.impl.jpa.JpaRepositoryFactory
persistence.persistenceUnit=eapli.alsafe
ui.menu.layout=vertical
jakarta.persistence.schema-generation.database.action=none
scomp.dir=./SCOMP
scomp.binary=flight_simulation
