#####################################################
##
## Base
##
#####################################################

persistence.repositoryFactory=eapli.alsafe.persistence.impl.jpa.JpaRepositoryFactory
#persistence.repositoryFactory=eapli.alsafe.persistence.impl.inmemory.InMemoryRepositoryFactory
persistence.persistenceUnit=eapli.alsafe
ui.menu.layout=vertical
HighCaloriesDishLimit=300